version: '3'
services:
  express-app:
    container_name: express-app
    restart: always
    build: .
    links:
      - mongo:mongo
    depends_on:
      - mongo
    volumes:
      - .:/app
      - ./logs:/root/.npm/_logs
    ports:
      - 3000:3000
  mongo:
    container_name: mongo-boilerplate
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fa12fnmar21!pq
    volumes:
      - ./mongo/data:/data/db
