// prettier-ignore
module.exports = {
  NOT_AUTHORIZED_ERROR_MESSAGE: "NOT_AUTHORIZED",
  AUTH_ERROR_MESSAGE: "LOGIN_OR_PASSWORD_INCORRECT",
  PASSWORD_MIN_LENGTH_EROR_MESSAGE: "PASSWORD_MIN_LENGTH_ERROR",
  PASSWORD_INCORRECT_ERROR_MESSAGE: "PASSWORD_INCORRECT",
  NEW_PASSWORD_CONFIRM_INCORRECT_ERROR_MESSAGE: "NEW_PASSWORD_CONFIRM_INCORRECT",
  IVENTORY_ITEM_ALREADY_EQUIP_ERROR_MESSAGE: "IVENTORY_ITEM_ALREADY_EQUIP",
  INVENTORY_ITEM_IS_IN_RENT_LOT_ERROR_MESSAGE: "INVENTORY_ITEM_IS_IN_RENT_LOT_ERROR_MESSAGE",
  IVENTORY_ITEM_ALREADY_UNEQUIP_ERROR_MESSAGE: "IVENTORY_ITEM_ALREADY_UNEQUIP",
  ITEM_ALREADY_EXISTS_ERROR_MESSAGE: "ITEM_ALREADY_EXISTS",
  CURRENT_USER_EMAIL_INCORRECT_ERROR_MESSAGE: "CURRENT_USER_EMAIL_INCORRECT",
  CURRENT_USER_EMAIL_DUPLICATE_ERROR_MESSAGE: "CURRENT_USER_EMAIL_DUPLICATE",
  ACTIVE_CONFIRMATION_EXIST_ERROR_MESSAGE: "ACTIVE_CONFIRMATION_EXIST",
  CHANGE_EMAIL_PROHIBITED_ERROR_MESSAGE: "CHANGE_EMAIL_PROHIBITED",
  CONFIRMATION_ALREDY_PROCESSED_ERROR_MESSAGE: "CONFIRMATION_ALREDY_PROCESSED",
  SHARE_TO_SAME_USER_ERROR_MESSAGE: "SHARE_TO_SAME_USER",
  ITEM_ALREDY_SHARING_ERROR_MESSAGE: "ITEM_ALREDY_SHARING",
  ITEM_NOT_SHARING_ERROR_MESSAGE: "ITEM_NOT_SHARING",
  CANCEL_SHARE_PROHIBITED_ERROR_MESSAGE: "CANCEL_SHARE_PROHIBITED",
  INVALID_SHARING_TAX_ERROR_MESSAGE: "INVALID_SHARING_TAX",
  USER_ALREADY_EXISTS_ERROR_MESSAGE: "USER_ALREADY_EXISTS",
  ROLE_ACCESS_DENIED_ERROR_MESSAGE: "ROLE_ACCESS_DENIED",
  FIELD_REQUIRED_ERROR_MESSAGE: "FIELD_REQUIRED",
  NOT_FOUND_ERROR_MESSAGE: "NOT_FOUND",
  INVALID_VALUE_ERROR: "INVALID_VALUE_ERROR",
  INVALID_UPLOAD_FILE_MIMETYPE_ERROR_MESSAGE: "INVALID_UPLOAD_FILE_MIMETYPE",

  // RENTING
  LOTID_REQUIRED: "LotId is required",
  USERID_REQUIRED: "UserId is required",
  LOT_NOT_FOUND: "Lot not found",
  RENT_FOR_LOT_CREATOR:"You cant rent for yourself",
  LOT_UNAVAILABLE: "Item already in use",


  INVENTORY_ID_REQUIRED: "inventoryId is required",
  USER_NOT_OWNER: "Only owner can create rent lot",
  ITEM_IS_EQUIPED: "Item is equipped",
  ITEM_ALREADY_RENTING: "Item already in rent",


  // CLICKER
  CLICKER_INVALID_SKILL_LEVEL_ERROR: "CLICKER_INVALID_SKILL_LEVEL_ERROR",
  CLICKER_LOBBY_END_STATUS_ERROR: "CLICKER_LOBBY_END_STATUS_ERROR",
  CLICKER_LOBBY_END_EXPIRED_ERROR: "CLICKER_LOBBY_END_EXPIRED_ERROR"
};
